name: main branch

on:
  push:
    branches:
    - main

jobs:
  unit-tests:
    uses: ./.github/workflows/unittest.yml

  action-test:
    needs: unit-tests
    uses: ./.github/workflows/action_test.yml
