name: on-pull-request

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm install
        run: npm install

      - name: Unit tests
        run: npm test
